### PR TITLE
Classification Model Improvements (TFIDF + TextCNN)

### PR DESCRIPTION
**Pull request by rdedhia**
## Summary

Updating documentation for allowed `model_type` and for allowed `base_model` under the `model_training_options` dict for CreateModelGroup API calls 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:
A quick checklist of things that should be done before the code is opened to review by others on the team.
Delete any that are not applicable.

- [x] Jira story/task is put into PR title
- [x] Code has been self-reviewed
- [x] Documentation has been updated

### CODE REVIEW

**Comment by goatrocks** [comment]
you should run `sphinx` and add the output to the PR so the docs will be updated

**Review by madisonmay — CHANGES_REQUESTED** [review]
Other than @goatrocks comment this LGTM.

**Comment by rdedhia** [comment]
> you should run `sphinx` and add the output to the PR so the docs will be updated

just added the html docs

**Comment by goatrocks** [comment]
@rdedhia looks like there's one conflict, could you resolve that and ping me and I'll get it merged?

**Pull request closed without merging**
